# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-10-23 08:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CmsUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('realname', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=200)),
                ('salt', models.CharField(help_text='password经过加盐进行md5加密', max_length=6, verbose_name='加盐值')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('work_address', models.CharField(blank=True, max_length=30, null=True)),
                ('phone', models.CharField(blank=True, max_length=11, null=True)),
                ('is_active', models.BooleanField(choices=[(1, 'active'), (0, 'forbid')], default=1, verbose_name='该用户是否启用 1:启用，2:禁止')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'manager_user',
            },
        ),
        migrations.CreateModel(
            name='CourseAdviserStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.BigIntegerField()),
                ('status', models.SmallIntegerField(choices=[(1, 'active'), (0, 'cancel')], default=1, verbose_name='状态')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='课程顾问接管学生时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='更换课程顾问时间')),
                ('cms_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CmsUser')),
            ],
            options={
                'db_table': 'course_adviser_student',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('type', models.SmallIntegerField(choices=[(1, 'level_1'), (2, 'level_2'), (3, 'level_3')], default=1, verbose_name='部门类型')),
                ('dept_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Department')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='ExtStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.BigIntegerField(verbose_name='学生id')),
                ('weixin', models.CharField(blank=True, max_length=30, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=30, null=True)),
                ('class_year', models.CharField(blank=True, max_length=30, null=True, verbose_name='年级')),
                ('school', models.CharField(blank=True, max_length=30, null=True)),
                ('school_nature', models.CharField(blank=True, max_length=30, null=True, verbose_name='学校性质')),
                ('source_channel', models.CharField(blank=True, max_length=30, null=True, verbose_name='来源渠道')),
                ('pay_action', models.SmallIntegerField(choices=[(1, '低'), (2, '中'), (3, '高')], default=1, verbose_name='付费意向')),
                ('age', models.SmallIntegerField(blank=True, null=True, verbose_name='年龄')),
                ('phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='年龄')),
                ('student_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='学生所在地')),
                ('equipment', models.CharField(blank=True, max_length=50, null=True, verbose_name='上课设备')),
                ('test_result', models.CharField(blank=True, max_length=30, null=True, verbose_name='检测结果')),
                ('test_time', models.DateTimeField(blank=True, null=True, verbose_name='检测时间')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ext_student',
            },
        ),
        migrations.CreateModel(
            name='LearnManagerStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.BigIntegerField()),
                ('status', models.SmallIntegerField(choices=[(1, 'active'), (0, 'cancel')], default=1, verbose_name='接受情况')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='学管老师接管学生时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='更换学管老师时间')),
                ('cms_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CmsUser')),
            ],
            options={
                'db_table': 'learn_manager_student',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.SmallIntegerField()),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('url', models.CharField(blank=True, default='', max_length=50)),
                ('url_name', models.CharField(blank=True, default='', max_length=30)),
                ('is_menu', models.BooleanField(choices=[(1, 'menu'), (0, 'button')], default=1)),
                ('icon', models.CharField(max_length=300)),
                ('aParent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='users.Menu')),
            ],
            options={
                'db_table': 'menu',
                'ordering': ['sort'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('code', models.CharField(blank=True, choices=[('course_adviser', '课程顾问'), ('learn_manager', '学管老师'), ('admin', '系统管理员'), ('super_admin', '超级管理员')], default='', max_length=20, null=True)),
                ('description', models.CharField(default='', max_length=200)),
                ('status', models.SmallIntegerField(choices=[(1, 'active'), (0, 'forbid')], default=1, verbose_name='角色是否启用')),
                ('is_super', models.BooleanField(choices=[(1, 1), (0, 0)], default=0)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Department')),
                ('menu', models.ManyToManyField(blank=True, null=True, to='users.Menu')),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.CreateModel(
            name='StudentRemark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=200, verbose_name='备注内容')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('student', models.BigIntegerField(verbose_name='学生')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CmsUser')),
            ],
            options={
                'db_table': 'student_remark',
            },
        ),
        migrations.CreateModel(
            name='VirtualclassException',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('virtual_class_id', models.BigIntegerField(verbose_name='virtualclass_id')),
                ('reason', models.SmallIntegerField(choices=[(1, '学生缺席'), (2, '老师缺席')])),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('cms_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.CmsUser')),
            ],
            options={
                'db_table': 'virtualclass_exception',
            },
        ),
        migrations.AddField(
            model_name='cmsuser',
            name='role',
            field=models.ManyToManyField(blank=True, null=True, to='users.Role'),
        ),
    ]
